# Generated by Django 6.0 on 2026-01-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpolyeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=50)),
                ('E_Email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('E_Address', models.TextField()),
                ('Company', models.CharField(max_length=100)),
                ('Sallary', models.IntegerField()),
                ('Jobrol', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
